openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for the authentication, which includes opeartion for creating/deleting account and login/logout.

servers:
  - url: http://.../auth
paths:
  /signup:
    post:
      summary: Creazione account
      parameters:
        - name: username
          in: query
          required: true
          description: Username of the new player
          schema:
            type: string
        - name: password
          in: query
          required: true
          description: Password of the new player
          schema:
            type: string
        - name: email
          in: query
          required: true
          description: Email of the new player
          schema:
            type: string
      responses:
        '200':
          description: Account created successfully
        '400':
          description: Bad request. All parameters must be strings

  /login:
    put:
      summary: Login of a player/admin
      parameters:
        - name: username
          in: query
          required: true
          description: Username of the player/admin
          schema:
            type: string
        - name: password
          in: query
          required: true
          description: Password of the player/admin
          schema:
            type: string
      responses:
        '200':
          description: Login success
        '400':
          description: Bad request. All parameters must be strings
        '404':
          description: Invalid credentials

  /logout:
    put:
      summary: Logout of player/admin
      responses:
        '200':
          description: Logout success

  /delete:
    delete:
      summary: Elimination of an existing account
      parameters:
        - name: username
          in: query
          required: true
          description: Username of the player to be deleted
          schema:
            type: string
        - name: password
          in: query
          required: true
          description: Password of the player to be deleted
          schema:
            type: string
      responses:
        '200':
          description: Account deleted successfully
        '400':
          description: Error in the elimination of the account
        '404':
          description: User not found
