openapi: 3.0.0
info:
  title: Gacha System API
  version: 1.0.0
  description: API per la gestione delle collezioni di gacha del sistema. Consente ai giocatori di vedere la collezione globale di gacha e di ottenere informazioni sui gacha mancanti.

servers:
  - url: http://.../gatchasystem

paths:

  /systemgachacollection:
    get:
      summary: Get the details of a specific system gacha
      description: Retrieve the detailed information of a specific gacha from the system collection or if the gacha_id is not set, retrieve all the entire gatcha collection.
      parameters:
        - name: gacha_id
          in: query
          required: false
          description: ID of the specific gacha from the system collection to get its details.
          schema:
            type: string
      responses:
        '200':
          description: Gacha details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gacha_id:
                    type: string
                  gacha_name:
                    type: string
                  description:
                    type: string
                  rarity:
                    type: string
                  collected_date:
                    type: string
                  img:
                    type: string
                    format: uri
        '401':
          description: User not authorized
        '404':
          description: Gacha not found

  /modify_gachacollection:
    patch:
      summary: Modification of the gacha collection (Administrator only)
      description: >
        Allows an administrator to modify the system's gacha collection. The administrator can update the details of an existing gacha or remove it from the collection.
      parameters:
        - name: gacha_id
          in: query
          required: true
          description: Gacha ID of the gacha to modify or remove
          schema:
            type: string
        - name: action
          in: query
          required: true
          description: Specify 'update' to modify an existing gacha, or 'remove' to remove a gacha from the collection and 'add' to add a new gatcha
          schema:
            type: string
            enum: [update, remove, add]
        - name: gacha_name
          in: query
          required: false
          description: Gacha name (required only when updating an existing gacha)
          schema:
            type: string
        - name: description
          in: query
          required: false
          description: Gacha description (required only when updating an existing gacha)
          schema:
            type: string
        - name: rarity
          in: query
          required: false
          description: Gacha rarity (required only when updating an existing gacha)
          schema:
            type: string
        - name: img
          in: query
          required: false
          description: immage
          schema:
            type: string
            format: uri 
      responses:
        '200':
          description: Gacha collection modified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Gacha updated successfully."
        '400':
          description: Invalid request (missing or incorrect fields)
        '403':
          description: Access forbidden for non-administrators
        '404':
          description: Gacha not found (for removal requests)
          

  
 