openapi: 3.0.0
info:
  title: Gacha System API
  version: 1.0.0
  description: API per la gestione delle collezioni di gacha del sistema. Consente ai giocatori di vedere la collezione globale di gacha e di ottenere informazioni sui gacha mancanti.

servers:
  - url: http://.../gatcharoll

paths:
    /gacharoll:
    post:
      summary: Use in-game currency to roll a gacha
      description: Allows a player to spend in-game currency to roll a gacha, potentially adding a new gacha to their collection.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The player's username who wants to roll the gacha.
                rarity:
                  type: string
                  description: The rarity of the roll.
                currency_amount:
                  type: integer
                  description: The amount of in-game currency used for the roll.
      responses:
        '200':
          description: Gacha rolled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gacha_id:
                    type: string
                  gacha_name:
                    type: string
                  description:
                    type: string
                  rarity:
                    type: string
                  collected_date:
                    type: string
                  img:
                    type: string
                    format: uri
                  message:
                    type: string
                    example: "You successfully rolled a new gacha!"
        '400':
          description: Insufficient in-game currency or invalid request