openapi: 3.0.0
info:
  title: Gacha System API
  version: 1.0.0
  description: API per la gestione delle collezioni di gacha del sistema. Consente ai giocatori di vedere la collezione globale di gacha e di ottenere informazioni sui gacha mancanti.

servers:
  - url: http://.../gatchasystem

paths:
  /get_gacha_collection:
    get:
      summary: Get the details of a specific system gacha
      description: Retrieve the detailed information of a specific gacha from the system collection or if the gacha_id is not set, retrieve all the entire gatcha collection.
      parameters:
        - name: gacha_name
          in: query
          required: false
          description: Name of the meme to get its details
          schema:
            type: string
      responses:
        '200':
          description: Gacha details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gacha_id:
                    type: string
                  gacha_name:
                    type: string
                  description:
                    type: string
                  rarity:
                    type: string
                  collected_date:
                    type: string
                  img:
                    type: string
                    format: uri
        '401':
          description: User not authorized
        '404':
          description: Gacha not found

  /add_gacha:
    post:
      summary: Add a gacha to the system (administrator only)
      description: Allows an administrator to add a gacha the collection.
      parameters:
        - name: image
          in: query
          required: true
          description: immage
          schema:
            type: string
            format: uri 
        - name: gacha_name
          in: query
          required: true
          description: Name for the meme
          schema:
            type: string
        - name: rarity
          in: query
          required: true
          description: Gacha rarity 
          schema:
            type: string
        - name: description
          in: query
          required: false
          description: Description of the meme
          schema:
            type: string
      responses:
        '200':
          description: Gacha collection updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Gacha added successfully."
        '400':
          description: Invalid request (missing or incorrect fields) or meme already exists
        '403':
          description: Access forbidden for non-administrators

  /delete_gacha:
    delete:
      summary: Remove a gacha from the collection  (administrator only)
      description: Allows an administratore to remove a gacha from the collection.
      parameters:
        - name: gacha_name
          in: query
          required: true
          description: Name of the meme
          schema:
            type: string
      responses:
        '200':
          description: Gacha removed successfully 
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Gacha removed successfully."
        '400':
          description: Invalid request (missing or incorrect fields)
        '403':
          description: Access forbidden for non-administrators
        '404':
          description: Gacha not found
        '500':
          description: Faild elaborating the request

  /update_gacha:
    put:
      summary: Update a gacha (Administrator only)
      description: The administrator can update the details of an existing gacha.
      parameters:
        - name: gacha_name
          in: query
          required: true
          description: Name of the meme
          schema:
            type: string
        - name: rarity
          in: query
          required: false
          description: New rarity of the gacha
          schema:
            type: string
        - name: description
          in: query
          required: false
          description: New description of the gacha
          schema:
            type: string
      responses:
        '200':
          description: Gacha updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Gacha updated successfully."
        '400':
          description: Invalid request (missing or incorrect fields)
        '403':
          description: Access forbidden for non-administrators
        '404':
          description: Gacha not found
          

  
 