openapi: 3.0.0
info:
  title: Gacha Roll API
  version: 1.0.0
  description: API that allows a user to roll and obtain a gacha.

servers:
  - url: https://localhost:5007/gacha_roll

paths:
  /gacharoll:
    post:
      summary: Perform a gacha roll for a user
      description: |
        Allows a user to perform a gacha roll at a specified level. 
        The system remove the required amount from the user's account, retrieves a gacha interacting with Gacha System, and adds it to the user's profile.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication. Format: `Bearer <token>`.
          schema:
            type: string
      requestBody:
        description: JSON payload containing `username` and `level`.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the player performing the gacha roll.
                  example: "user1"
                level:
                  type: string
                  description: The level of the gacha roll. Can be 'standard', 'medium', or 'premium'.
                  enum: [standard, medium, premium]
                  example: "standard"
              required:
                - username
                - level
      responses:
        '200':
          description: Gacha roll completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  gacha_name:
                    type: string
                    description: Name of the gacha item obtained.
                  description:
                    type: string
                    description: Description of the gacha item.
                  rarity:
                    type: string
                    description: Rarity of the gacha item.
                  img:
                    type: string
                    description: URL of the gacha item's image.
                  collected_date:
                    type: string
                    format: date-time
                    description: The date and time when the gacha was collected.
        '400':
          description: Missing or invalid parameters (e.g., invalid level or missing username).
        '401':
          description: Unauthorized - Missing or invalid Authorization header.
        '403':
          description: The username in the token does not match the username in the request body.
        '500':
          description: Internal server error - Failure in payment, fetching gacha, or updating the profile.
        '503':
          description: Service unavailable.