services:
  auth_service_test:
    build:
      context: . 
      dockerfile: Dockerfile_test
    ports:
      - "5007:5007"
    secrets:
      - gacharoll_cert
      - gacharoll_key
    volumes:
      - ../RSAkeys:/app/RSAkeys:ro  # Monta la directory delle chiavi in sola lettura
    environment:
      # - DATABASE_URI=postgresql://user:password@auth_db:5432/auth_db
      #- JWT_SECRET_KEY=super-secret-key
      - PRIVATE_KEY_PATH=/app/RSAkeys/private_key.pem
      - PUBLIC_KEY_PATH=/app/RSAkeys/public_key.pem


volumes:
  auth_data:
secrets:
  gacharoll_cert:
    file: ./gacharoll_cert.pem
  gacharoll_key:
    file: ./gacharoll_key.pem